# Generated by Django 4.0.6 on 2022-07-25 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mo_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Imię')),
                ('surname', models.CharField(max_length=64, verbose_name='Nazwisko')),
                ('email', models.EmailField(max_length=254, verbose_name='e-mail')),
                ('phone', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Presence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mo_app.client')),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mo_app.workout')),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(1, 'pojedyncze wejście'), (2, '4 wybór'), (3, '4 otwarty'), (4, '8 wybór'), (5, '8 otwarty'), (6, '12 wybór'), (7, '12 otwarty'), (8, 'open')], verbose_name='Rodzaj')),
                ('start', models.DateTimeField(verbose_name='Ważny od')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mo_app.client')),
            ],
        ),
    ]
