# Generated by Django 4.0.6 on 2022-07-25 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mo_app', '0002_client_presence_membership'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='surname',
            field=models.CharField(default='brak', max_length=64, verbose_name='Nazwisko'),
            preserve_default=False,
        ),
    ]
